import sys

inp = sys.argv[1]
out = ''

smol = ['ゃ', 'ゅ', 'ょ']


for i in range(0, len(inp)):
	c = inp[i]
	if i != len(inp) - 1:
		if inp[i+1] in smol:
			c += inp[i+1]
			i += 1
	
	if c == 'あ': out += 'a' 
	elif c == 'い': out += 'i'
	elif c == 'う': out += 'u'
	elif c == 'え': out += 'e'
	elif c == 'お': out += 'o'
	elif c == 'か': out += 'ka'
	elif c == 'き': out += 'ki'
	elif c == 'く': out += 'ku'
	elif c == 'け': out += 'ke'
	elif c == 'こ': out += 'ko'
	elif c == 'さ': out += 'sa'
	elif c == 'し': out += 'shi'
	elif c == 'す': out += 'su'
	elif c == 'せ': out += 'se'
	elif c == 'そ': out += 'so'
	elif c == 'た': out += 'ta'
	elif c == 'ち': out += 'chi'
	elif c == 'つ': out += 'tsu'
	elif c == 'て': out += 'te'
	elif c == 'と': out += 'to'
	elif c == 'な': out += 'na'
	elif c == 'に': out += 'ni'
	elif c == 'ぬ': out += 'nu'
	elif c == 'ね': out += 'ne'
	elif c == 'の': out += 'no'
	elif c == 'は': out += 'ha'
	elif c == 'ひ': out += 'hi'
	elif c == 'ふ': out += 'fu'
	elif c == 'へ': out += 'he'
	elif c == 'ほ': out += 'ho'
	elif c == 'ま': out += 'ma'
	elif c == 'み': out += 'mi'
	elif c == 'む': out += 'mu'
	elif c == 'め': out += 'me'
	elif c == 'も': out += 'mo'
	elif c == 'や': out += 'ya'
	elif c == 'ゆ': out += 'yu'
	elif c == 'よ': out += 'yo'
	elif c == 'ら': out += 'ra'
	elif c == 'り': out += 'ri'
	elif c == 'る': out += 'ru'
	elif c == 'れ': out += 're'
	elif c == 'ろ': out += 'ro'
	elif c == 'わ': out += 'wa'
	elif c == 'を': out += 'wo'
	elif c == 'ん': out += 'n'
	elif c == 'が': out += 'ka'
	elif c == 'ぎ': out += 'gi'
	elif c == 'ぐ': out += 'gu'
	elif c == 'げ': out += 'ge'
	elif c == 'ご': out += 'go'
	elif c == 'ざ': out += 'za'
	elif c == 'じ': out += 'ji'
	elif c == 'ず': out += 'zu'
	elif c == 'ぜ': out += 'ze'
	elif c == 'ぞ': out += 'zo'
	elif c == 'だ': out += 'da'
	elif c == 'ぢ': out += 'ji'
	elif c == 'づ': out += 'zu'
	elif c == 'で': out += 'de'
	elif c == 'ど': out += 'do'
	elif c == 'ば': out += 'ba'
	elif c == 'び': out += 'bi'
	elif c == 'ぶ': out += 'bu'
	elif c == 'べ': out += 'be'
	elif c == 'ぼ': out += 'bo'
	elif c == 'ぱ': out += 'pa'
	elif c == 'ぴ': out += 'pi'
	elif c == 'ぷ': out += 'pu'
	elif c == 'ぺ': out += 'pe'
	elif c == 'ぽ': out += 'po'
	elif c == 'きゃ': out += 'kya'
	elif c == 'きゅ': out += 'kyu'
	elif c == 'きょ': out += 'kyo'
	elif c == 'ぎゃ': out += 'gya'
	elif c == 'ぎゅ': out += 'gyu'
	elif c == 'ぎょ': out += 'gyo'
	elif c == 'しゃ': out += 'sha'
	elif c == 'しゅ': out += 'shu'
	elif c == 'しょ': out += 'sho'
	elif c == 'じゃ': out += 'ja'
	elif c == 'じゅ': out += 'ju'
	elif c == 'じょ': out += 'jo'
	elif c == 'ちゃ': out += 'cha'
	elif c == 'ちゅ': out += 'chu'
	elif c == 'ちょ': out += 'cho'
	elif c == 'にゃ': out += 'nya'
	elif c == 'にゅ': out += 'nyu'
	elif c == 'にょ': out += 'nyo'
	elif c == 'ひゃ': out += 'hya'
	elif c == 'ひゅ': out += 'hyu'
	elif c == 'ひょ': out += 'hyo'
	elif c == 'びゃ': out += 'bya'
	elif c == 'びゅ': out += 'byu'
	elif c == 'びょ': out += 'byo'
	elif c == 'みゃ': out += 'mya'
	elif c == 'みゅ': out += 'myu'
	elif c == 'みょ': out += 'myo'
	elif c == 'ぴゃ': out += 'pya'
	elif c == 'ぴゅ': out += 'pyu'
	elif c == 'ぴょ': out += 'pyo'
	elif c == 'りゃ': out += 'rya'
	elif c == 'りゅ': out += 'ryu'
	elif c == 'りょ': out += 'ryo'
	
print(out)
